// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 07/12/2025, 14:26:20
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/richardnunesmachado/Documents/educaai-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richardnunesmachado/Documents/educaai-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richardnunesmachado/Documents/educaai-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richardnunesmachado/Documents/educaai-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richardnunesmachado/Documents/educaai-nuxt/plugins/**/*.{js,ts,mjs}","/Users/richardnunesmachado/Documents/educaai-nuxt/composables/**/*.{js,ts,mjs}","/Users/richardnunesmachado/Documents/educaai-nuxt/utils/**/*.{js,ts,mjs}","/Users/richardnunesmachado/Documents/educaai-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/richardnunesmachado/Documents/educaai-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/richardnunesmachado/Documents/educaai-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/richardnunesmachado/Documents/educaai-nuxt/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;